# ATA055 · udhcpd — servidor DHCP SEÑUELO (local, segmento aislado)
# Servido por busybox udhcpd SOLO en la interfaz vdhcp0 (par veth aislado).
# NO toca VMnet1 ni ens33; no compite con el DHCP de VMware.
start 10.99.0.100
end 10.99.0.110
interface vdhcp0
option subnet 255.255.255.0
option router 10.99.0.1
option dns 10.99.0.1
option broadcast 10.99.0.255
option lease 120
lease_file /home/angel/lab-attack/ATA055/udhcpd.leases
pidfile /home/angel/lab-attack/ATA055/udhcpd.pid
